# blacklist
branches:
  except:

# whitelist
branches:
  only:
    - master
    - presentation
    - FHV-Titlepage
sudo: required
services:
- docker
before_install:
- docker pull sumdoc/texlive-2017
- docker run -d --name ubuntu-test -v $(pwd):/travis sumdoc/texlive-2017 tail -f /dev/null
- docker ps
- openssl aes-256-cbc -K $encrypted_05f0f0336636_key -iv $encrypted_05f0f0336636_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=1 LANGUAGE=ngerman > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/DE_DOC_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/DE_DOC_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_DE_DOC_LatexVorlage.txt

- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=3 LANGUAGE=ngerman > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/DE_SUMMARY_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/DE_SUMMARY_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_DE_SUMMARY_LatexVorlage.txt

- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=5 LANGUAGE=ngerman > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/DE_PRE_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/DE_PRE_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_DE_PRE_LatexVorlage.txt

- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=9 LANGUAGE=ngerman > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/DE_PAPER_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/DE_PAPER_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_DE_PAPER_LatexVorlage.txt

- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=2 LANGUAGE=ngerman > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/DE_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/DE_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_DE_LatexVorlage.txt

- docker exec -t ubuntu-test bash -c "cd travis;
  make clean;
  make FHVMODE=2 LANGUAGE=english > log.txt;"
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${BRANCH_NAME}/EN_LatexVorlage-latest.pdf
- ./dropbox_uploader.sh upload build/LatexVorlage.pdf ${TRAVIS_BRANCH}/EN_LatexVorlage-${TRAVIS_JOB_NUMBER}.pdf
- ./dropbox_uploader.sh upload log.txt log/${TRAVIS_BRANCH}-${TRAVIS_JOB_NUMBER}_EN_LatexVorlage.txt
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: NphQ8EAmIv1NiYwkZ1Ay0Kqy+yoNvFZ+MB3wtEGYAHy5tKg9SdF1L5awo3oGnf7mQSiP7UaOZhUbe4NgvsMQMvxxox/aAYQBroHXbZDE/vaxAUeQ+UX3NQPbStfdnNGYEsXuMNvEUPfS31w7jP7Im1FFWHNrPBDKBgot+vO6IP2GP2eQCyUPG0VSTQa5+JFfdz1zkIjPBXTTVHWbfKivSMDNKoqAIYxKzWtjuH6iajHCNZVTrGsm7EOauIul7KVeuPASlfwo1fORAGpVuavHf8JDMd+Wh39VUOqMN7+AxpP0oOis4rh4svn8/tpFq7SzQUrTeh8RJgDIqKGoRLBTpgZZzrACf1JAQAya4C7whjtvhI2Wv3H7VvNPJZ38VH+Zicyg8+VNotKcC1jszimPAUWFr6cDakkOeSQNGvBUNAzaL3riOUtL45cqPt2bawTAqsP/PvcPkGcpbdHtJ2Tvsi551NeD0MP/wA5Gll245lUGu36Q19vWiX3MMLY+GCrz9r2foJKi1v5qA8mLns63f6Z+Ceu6RswetGHNOCC0sSfVDEdllQM2R+1OZr44IicZzhxP+kfsUtBOEubayBHvMq/Lpkah+hngUJzrqlZfEqTFb4SisqJwGoh5DPfUTI0ffKDjgrVq1D8/Vq3nHHQNK9yL6ZLVRWMZ4KqQ7wm5nyw=
  file: "./build/LatexVorlage.pdf"
  skip_cleanup: true
  on:
    repo: pasrom/FHV-Latex
    tags: true
