# blocklist
branches:
  except:
  - master
# safelist
branches:
  only:
  - travis-integration

sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra texlive-lang-german texlive-generic-extra biber --no-install-recommends
script:
- pdflatex -interaction=nonstopmode -halt-on-error *.tex