# blocklist
branches:
  except:
  - master
# safelist
branches:
  only:
  - travis-integration

sudo: required
dist: trusty
before_install:
- sudo add-apt-repository -y ppa:jonathonf/texlive-2016
- sudo apt-get update
#- sudo apt-get -qq update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra texlive-lang-german texlive-generic-extra biber
- sudo apt-get install -y --no-install-recommends texlive texlive-lang-german biber #texlive-extra-utils texlive-latex-extra texlive-generic-extra texlive-math-extra biber
#- sudo apt-get install -y texlive-science
#- sudo apt-get install -y texlive-fonts-extra 
#- sudo apt-get install -y texlive-lang-german
#- sudo apt-get install texlive-lang-german
- sudo apt-get install -y xzdec
- tlmgr init-usertree
- tlmgr install bondgraphs logreq biblatex german babel-german currfile filehook pgf subfiles
- tlmgr install blindtext lipsum circuitikz mwe xpatch
- tlmgr list --only-installed
script:
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
- biber --output_directory ./build/ LatexVorlage
- biber --output_directory ./build/ LatexVorlage
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
#- makeglossaries "./build/LatexVorlage.idx"