# blocklist
branches:
  except:
  - master
# safelist
branches:
  only:
  - travis-integration

sudo: required
dist: xenial
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive-2017-trusty -y
- sudo apt-get update
#- sudo apt-get -qq update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra texlive-lang-german texlive-generic-extra biber
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-science
- sudo apt-get install -y texlive-fonts-extra 
- sudo apt-get install -y xzdec
- tlmgr init-usertree
- tlmgr install bondgraphs
script:
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
- biber --output_directory ./build/ LatexVorlage
- biber --output_directory ./build/ LatexVorlage
- pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex
#- makeglossaries "./build/LatexVorlage.idx"