sudo: required

services:
  - docker

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
    add-apt-repository -y ppa:jonathonf/texlive-2017;
    apt-get update;
    apt-get install -y texlive-full;
    apt-get install -y xzdec"
 
script:
  - docker exec -t ubuntu-test bash -c "cd travis;
      pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex;
      pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex;
      biber --output_directory ./build/ LatexVorlage;
      biber --output_directory ./build/ LatexVorlage;
      makeglossaries ./build/LatexVorlage.idx;
      pdflatex -shell-escape -recorder -synctex=1 -interaction=nonstopmode -output-directory=./build/ LatexVorlage.tex"

notifications:
    email: false